//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiaZaiWZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public string AdminName { get; set; }
        public string AdminPwd { get; set; }
        public string LoginTime { get; set; }
        public string Adder { get; set; }
        public string Ip { get; set; }
    }
}
