//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XiaZaiWZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public int Size { get; set; }
        public string SizeNum { get; set; }
        public string Uptime { get; set; }
        public string Format { get; set; }
        public string Content { get; set; }
        public string DownUrl { get; set; }
        public string Tong { get; set; }
        public Nullable<int> Cls1_id { get; set; }
        public Nullable<int> Cls2_id { get; set; }
        public List<View> SecondaryCategoryac { get; set; }
    }
}
